<?php dev_dd('32', 123); ?>
<div id="modal_dialog_message" class="vendor-popup">
    <?php if ($vendor = $block->getVendor()): ?>
    <div class="fieldset">
        <table cellspacing="0" class="info-list">
            <tbody>
                <tr>
                    <td class="label"><label>Customer Service Email</label></td>
                    <td id="merchant-email" class="value"><?= $vendor->getEmail() ?></td>
                </tr>
                <tr>
                    <td class="label"><label>Customer Service Phone Number</label></td>
                    <td id="merchant-phone" class="value"><?= $vendor->getTelephone() ?></td>
                </tr>
                <tr>

                    <td class="label"><label>Customer Service Street</label></td>
                    <td id="merchant-street" class="value"><?= $vendor->getStreet() ?></td>
                </tr>
                <tr>
                    <td class="label"><label>Customer Service City</label></td>
                    <td id="merchant-city" class="value"><?= $vendor->getCity() ?></td>
                </tr>
                <tr>
                    <td class="label"><label>Customer Service Postcode</label></td>
                    <td id="merchant-postcode" class="value"><?= $vendor->getPostalCode() ?></td>
                </tr>
                <tr>
                    <td class="label"><label>Customer Service Country</label></td>
                    <td id="merchant-country" class="value"><?= $vendor->getCountry() ?></td>
                </tr>
            </tbody>
        </table>
    </div>
    <?php endif ?>
</div>
