<?php

// @codingStandardsIgnoreFile

/** @var \Mageinn\Dropship\Block\Adminhtml\ShippingRates\ImportExport $block*/
?>
<div class="import-export-shipping-rates">
    <div class="import-shipping-rates">
        <div class="admin__page-section-title">
            <span class="title"><?= /* @escapeNotVerified */ __('Import Shipping Rates') ?></span>
        </div>
        <form id="import-form" class="admin__fieldset shipping-rates-form" action="<?= $block->getImportUrl() ?>" method="post" enctype="multipart/form-data">
            <?= $block->getBlockHtml('formkey') ?>
            <div class="fieldset admin__field">
                <span class="admin__field-label"><span><?= /* @escapeNotVerified */ __('Select Dropship') ?></span></span>
                <div class="admin__field-control">
                    <?= $block->getVendorsSelectHtml() ?>
                    <input type="file" id="shipping_rates_file" name="shipping_rates_file" class="input-file required-entry"/>
                    <?= $block->getButtonHtml(__('Import'), 'this.form.submit()', 'import-submit primary') ?>
                </div>
            </div>
        </form>
    </div>
    <div class="export-shipping-rates">
        <div class="admin__page-section-title">
            <span class="title"><?= /* @escapeNotVerified */ __('Export Shipping Rates') ?></span>
        </div>
        <form id="export_form" class="admin__fieldset shipping-rates-form" action="<?= $block->getExportUrl() ?>" method="post" enctype="multipart/form-data">
            <?= $block->getBlockHtml('formkey') ?>
            <div class="fieldset admin__field">
                <span class="admin__field-label"><span><?= /* @escapeNotVerified */ __('Select Dropship') ?></span></span>
                <div class="admin__field-control">
                    <?= $block->getVendorsSelectHtml() ?>
                    <?= $block->getButtonHtml(__('Export'), "this.form.submit()", 'primary') ?>
                </div>
            </div>
        </form>
    </div>
</div>
